config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # SEE ALL
  get '/pets', to: 'pets#index', as: :pets

  # receive the form
  post '/pets', to: 'pets#create'

  # CREATE
  # display the form
  get '/pets/new', to: 'pets#new', as: :new_pet




  # UPDATE
  # display the form
  get '/pets/:id/edit', to: 'pets#edit', as: :edit_pet

  # SEE DETAILS ABOUT ONE (read one)
  get '/pets/:id', to: 'pets#show', as: :pet
  # receive the form
  patch '/pets/:id', to: 'pets#update'

  delete '/pets/:id', to: 'pets#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ['dog', 'cat', 'pig', 'bird', 'dragon', 'hamster', 'bat']

  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    @pets = Pet.all
  end

  def show
    # FIND THE RIGHT INSTANCE
    @pet = Pet.find(params[:id])
  end

  def new
    # CREATE THE EMPTY INSTANCE TO BE USED IN THE FORM
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save

    redirect_to pet_path(@pet) #=> /pets/:id
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)

    redirect_to pet_path(@pet) #=> /pets/:id
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy

    redirect_to pets_path, status: :see_other
  end

  private

  # STRONG PARAMS!!!
  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets1408</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for pet do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :found_on %>
        <%= f.input :species, collection: Pet::SPECIES %>
        <%= f.submit %>
      <% end %>

    </div>
  </div>
</div>

app/views/pets/edit.html.erb
<h1>Update <%= @pet.name %></h1>

<%= render 'form', pet: @pet %>

app/views/pets/index.html.erb
<h1>Did you lost your pet?</h1>

<ul>
  <% @pets.each do |pet| %>
    <li><%= link_to pet.name, pet_path(pet) %> | <%= link_to 'Edit', edit_pet_path(pet) %> | <%= link_to 'Remove', pet_path(pet), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{pet.name}" } %></li>
  <% end %>
</ul>

<%= link_to 'Report a lost pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>Report a pet</h1>

<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<p>Address: <%= @pet.address %></p>
<p>Species: <%= @pet.species %></p>
<p>Found on: <%= @pet.found_on %></p>

<%= link_to 'Back to all pets', pets_path %>